### ISSUE TITLE
Default color order different from plotly

### ISSUE THREAD

**Issue by mazzma12** [santosjorge/cufflinks#110]
Hi, 

I wonder why the default colour order with `cufflinks` is not the same as `plotly`. 
Do you have a reason for that? I think it should be the same for consistency: if you have 2 versions of the same plot using `cufflinks` or `plotly` it can be misleading at the first sight.

For an example see the [boxplots page](https://plot.ly/pandas/box-plots/)

**Comment by santosjorge** [comment]
Hi @mazzma12  - no particular reason. The colors selected are based on themes that I used when I started developing this library. I don't think that at this stage it would be a good idea to change the default set of colors used. 
However, you can always create your own colorscales and set them as default. 

```
cf.set_config_file(colorscale='your_colorscale_name')
```

**Comment by mazzma12** [comment]
Thank you, I will try this and see if I can match plotly colors
