### ISSUE TITLE
Multiindex and cufflinks

### ISSUE THREAD

**Issue by mcrone** [santosjorge/cufflinks#111]
Hey

I've had some problems with a multiindex dataframe and cufflinks because I am not able to specify what I would like to be plotted as mean and what I would like to be plotted as error.

This is my dataframe:
![image](https://user-images.githubusercontent.com/4923807/39677556-30a23a80-517d-11e8-8445-33022085f490.png)

As you can see I have the mean and standard deviation of different samples over time. I would like to display the mean with the standard deviation as continuous error (or just error bars). With cufflinks I am not sure that this is currently possible because I end up with this:

![image](https://user-images.githubusercontent.com/4923807/39677522-936f0a4a-517c-11e8-9f1e-06b1ccf1fb17.png)

Perhaps I am just missing something.

**Comment by santosjorge** [comment]
Hi @mcrone , did you try what @mazzma12 suggested? 
Unstacking the `DataFrame` should allow you to do this easily. 
Otherwise if you can share the code with which you are generating your `DataFrame`

**Comment by mcrone** [comment]
Thank you for the help @mazzma12!

I was specifying my dataframe with the code below just because of the formatting of the data from a csv:

`d = df.groupby('Time [min]').agg(['mean', 'std']).T`

I got around the problem with this code:

`[{'x': d.xs('mean', level = 1).index.get_level_values(0),
    'y': d.xs('mean', level = 1)[col],
    'name': col,
    'error_y':dict(
        type='continuous_data',
        array=d.xs('std', level = 1)[col])
}  for col in d.columns]`

I will try your suggest since it is probably a cleaner way of doing it. (Sorry for the messy code, for some reason I can't seem to insert linebreaks)

Here was my final graph:
![image](https://user-images.githubusercontent.com/4923807/41206390-a0b6bebc-6d03-11e8-881e-fb18fe98f3b5.png)

**Comment by mcrone** [comment]
This seems to have broken again with the new plotly and cufflinks. I followed the suggestion and unstacked the columns and so I end up with this:

![image](https://user-images.githubusercontent.com/4923807/47463500-4ed39200-d7de-11e8-9f08-0c67fb447d30.png)

The only way that I seem to be able to plot it is by dropping the column with the standard deviation with: `av=d.drop('std', level=1, axis=1)` and then plotting this: `av.iplot(kind='scatter', filename='cufflinks/simple-line')` however then I am unsure of how to add in the error again.

It seems that the error suggested in the readme for version 0.6 doesn't seem to work any longer, or perhaps I just don't understand how to plot varying error for each trace.

**Comment by mcrone** [comment]
Ok I fixed this by doing it the non cufflinks way:

![image](https://user-images.githubusercontent.com/4923807/47491706-4e211700-d843-11e8-9e84-1834689fd243.png)
