### ISSUE TITLE
qf.iplot() --> error: PlotlyDictKeyError: 'showlegend' is not allowed in 'increasing'

### ISSUE THREAD

**Issue by DandiestWaffle** [santosjorge/cufflinks#113]
Can you point me in the right direction to resolve this error I get from qf.iplot()?
 - Thank you for the wonderful library and documentation and fantastic presentation at pycon. 
 - Your work effort here makes data analysis with plotly much more efficient and for this I thank thank you.

## Issue
running `qf.iplot()` in Jupyter Notebook produces error

## Code that produces error
```
import pandas as pd
import cufflinks as cf
import numpy as np

df=cf.datagen.ohlc()
qf=cf.QuantFig(df,title='First Quant Figure',legend='top',name='GS')
qf.add_bollinger_bands(periods=20,boll_std=2,colors=['magenta','grey'],fill=True)
qf.iplot()
```

## Error
> PlotlyDictKeyError: 'showlegend' is not allowed in 'increasing'
> 
> Path To Error: ['data'][0]['increasing']['showlegend']
> 
> Valid attributes for 'increasing' at path ['data'][0]['increasing'] under parents ['figure', 'data', 'candlestick']:
> 
>     ['fillcolor', 'line']
> 
> Run `<increasing-object>.help('attribute')` on any of the above.
> '<increasing-object>' is the object at ['data'][0]['increasing']

[complete code and error output.txt](https://github.com/santosjorge/cufflinks/files/2049508/complete.code.and.error.output.txt)

**my environment:**
python: 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
IPython: (6, 2, 1, '')
pandas: 0.22.0
cufflinks: 0.12.1
numpy: 1.14.0

**Comment by joelkim** [comment]
+1 me too.

my environment

Python 3.6.5 :: Anaconda custom (64-bit)
plotly                    2.7.0                    py36_1    anaconda
cufflinks-py              0.12.1                     py_0    conda-forge

**Comment by santosjorge** [comment]
Nevermind. I see the issue now. Will fix it.

**Comment by michaelazer** [comment]
> Nevermind. I see the issue now. Will fix it.

Can you share your solution, because I believe I have the same issue?
Thanks
