### ISSUE TITLE
cufflinks incorrectly init_notebook_mode when offline

### ISSUE THREAD

**Issue by djchou** [santosjorge/cufflinks#117]
I'm using cufflinks from a script and "import cufflinks" automatically pollutes my screen with injected javascript as triggers plotly's init_notebook_mode function.

There should be a way to be offline without triggering the init_notebook_mode function.  Perhaps add a config option that doesnt trigger init_notebook_mode?

**Comment by mazzma12** [comment]
Hi, never witnessed that, do you have a script that could reproduce it?

**Comment by santosjorge** [comment]
Hi @djchou - which version are you using? This was already fixed on #105

**Comment by djchou** [comment]
I must be using an old version.  Going to close
