### ISSUE TITLE
yTitle not showing up when secondary_y is present

### ISSUE THREAD

**Issue by tirada** [santosjorge/cufflinks#125]
When I use a secondary_y to create a secondary axis in the plot it ignores and does not label the primary axis (yTitle) however the secondary axis(secondary_y_title) is labelled. 

My code goes as follows:
`fig1 = df[['x','y']].iplot(kind='bar', asFigure=True)
fig2 = df['z'].iplot(kind='scatter', barmode='stack', xTitle='Dates', title='Random Chart', colors=['red'],
                             secondary_y='z', yTitle='Volume', secondary_y_title='Price', asFigure=True)
fig2['data'].extend(fig1['data'])
plot(fig2, filename='Random_Chart')`

**Comment by santosjorge** [comment]
Hi @tirada ,

I don't see an issue when using both axis titles

```python
cf.datagen.lines(2).iplot(kind='lines',secondary_y='b',secondary_y_title='left axis',yTitle='right axis')
```

![2018-08-31_00-08-52](https://user-images.githubusercontent.com/2511100/44884155-233a9c80-acb2-11e8-852e-3c8b96272e63.png)

For combining figures you can either use `cf.tools.merge_figures` or `cf.tools.figures` 

For example

```python
data=cf.datagen.lines(3)
cf.tools.figures(data,[dict(kind='bar',columns=['a','b'],yTitle='bar axis'),
                       dict(kind='lines',columns='c',secondary_y='c',secondary_y_title='line axis',color='magenta',
                            width=2)]).iplot()
```

![2018-08-31_00-13-16](https://user-images.githubusercontent.com/2511100/44884304-b2e04b00-acb2-11e8-8821-5d1f34ae396c.png)


Let me know if this is not what you are looking for please.

**Comment by santosjorge** [comment]
Please reopen if needed
