### ISSUE TITLE
QuantFigure incorrect scaling when adding hline through qf.add_shapes()

### ISSUE THREAD

**Issue by ghost** [santosjorge/cufflinks#126]
Using one of the cufflink examples, and then trying to save a .html file of the figure:
```
import cufflinks as cf
import plotly as py

cf.go_offline()
df = cf.datagen.ohlc()
qf = cf.QuantFig(df, title='First Quant Figure', legend='top', name='GS')
qf.add_shapes(hline=[10, 40])
fig = qf.iplot(asFigure=True)
# fig['layout']['yaxis2']['side'] = 'right'
py.offline.plot(fig, filename='error.html')
```
 gives me the following:

![image](https://user-images.githubusercontent.com/13710187/44319588-4d4cbd00-a46f-11e8-9c6b-b97f489a35d3.png)

You can uncomment the line:  `# fig['layout']['yaxis2']['side'] = 'right'` to better understand the issue.

I see something similar with the functions QuantFigure.add_support and add_resistance as well:

```
import cufflinks as cf
import plotly as py

cf.go_offline()
df = cf.datagen.ohlc()
print(df.head())
qf = cf.QuantFig(df, title='First Quant Figure', legend='top', name='GS')
# qf.add_shapes(hline=[10, 40])
qf.add_support('2015-01-04')
fig = qf.iplot(asFigure=True)
# fig['layout']['yaxis2']['side'] = 'right'
py.offline.plot(fig, filename='error.html')
```
![image](https://user-images.githubusercontent.com/13710187/44319730-378bc780-a470-11e8-989b-d22fc92725c8.png)

I've found Cufflinks to be a fantastic library for financial time-series analysis related work. Also pretty sure you guys would be swamped with other work. If any of the maintainers could let me know how to approach this issue, would be v happy to submit a pull request with the fixes. 

Many thanks

**Comment by santosjorge** [comment]
Fixed on 13.3
