### ISSUE TITLE
Requiring 'core' in python 3.4.3

### ISSUE THREAD

**Issue by juanklopper** [santosjorge/cufflinks#13]
Using newest Ananconda install with python 3.4.3.  In notebook !pip install cufflinks works, but importing set_confog_file return erros requiring datetool.  This install sucessfully also using !pip install, but importing set_config_file then requires core.  Install of core returns: Could not find a version that satisfies the requirement core (from versions: )
No matching distribution found for core

**Comment by santosjorge** [comment]
Hi Juan - Yes I haven't tested this in 3.x 
There but will do in the next version.

**Comment by gpillemer** [comment]
Just had the same issue as above - hanging out for a Python 3 update!
Thanks.

**Comment by kkalantar** [comment]
I have also encountered the same issue as above. Will wait for the update, thanks!

**Comment by santosjorge** [comment]
Version 0.7.0 support Python 3 now :)

**Comment by gpillemer** [comment]
Awesome!
Thanks so much for this work!

**Comment by juanklopper** [comment]
Great!

**Comment by chriddyp** [comment]
:100: thanks!
