### ISSUE TITLE
ImportError: cannot import name 'FigureWidget'

### ISSUE THREAD

**Issue by mmrahn** [santosjorge/cufflinks#130]
I just cloned the new cufflinks version 0.14.0 which is supposed to be compatible with plotly. 
When trying to import cufflinks, I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\monar\Miniconda3\envs\athion-utils\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-f6fce55a6101>", line 1, in <module>
    import cufflinks
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\monar\Miniconda3\envs\athion-utils\lib\site-packages\cufflinks\__init__.py", line 21, in <module>
    from .plotlytools import *
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\monar\Miniconda3\envs\athion-utils\lib\site-packages\cufflinks\plotlytools.py", line 6, in <module>
    from plotly.graph_objs import Figure, Bar, Box, Scatter, FigureWidget, Scatter3d, Histogram, Heatmap, Surface, Pie
ImportError: cannot import name 'FigureWidget'
```
My plotly version is 3.1.1.

**Comment by santosjorge** [comment]
Hi @mmrahn - 
Are you running this from a Jupyter Notebook / JupyterLab? 
Can you run directly 
```python
from plotly.graph_objs import FigureWidget
```
?

**Comment by mmrahn** [comment]
No, I'm not using Jupyter. I'm running it from PyCharm (sometimes in an ipython console, sometimes with the regular python interpreter).

No, I can't:
```
from plotly.graph_objs import FigureWidget
Traceback (most recent call last):
  File "C:\Users\monar\Miniconda3\envs\clone-athion-utils\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-26cd651ce7af>", line 1, in <module>
    from plotly.graph_objs import FigureWidget
ImportError: cannot import name 'FigureWidget'
```

**Comment by mmrahn** [comment]
Okay, after a bit of digging, it turns out that `FigureWidget` cannot be imported because I didn't have `ipywidgets` installed. After installing it, I can both import `FigureWidget` and `cufflinks`.

Maybe add it to the requirements in `setup.py`?

**Comment by mmrahn** [comment]
Same goes for `ipython` btw: It is needed to import cufflinks but not included in the requirements.

**Comment by timkpaine** [comment]
feel free to make a pull request

**Comment by timkpaine** [comment]
#132

**Comment by santosjorge** [comment]
Thank you @timkpaine

**Comment by mmrahn** [comment]
@santosjorge I think this does not resolve the error because `ipywidgets` is still not added in the requirements.txt.
Minimal example:

conda create -n test python=3.6
conda activate test
pip install cufflinks~=0.14.1
ipython
```
import cufflinks
```
raises
```
ImportError: cannot import name 'FigureWidget'
```

**Comment by timkpaine** [comment]
thats a transitive dependency through plotly

**Comment by timkpaine** [comment]
meaning plotly should enforce it

**Comment by timkpaine** [comment]
import:
https://github.com/plotly/plotly.py/blob/master/plotly/basewidget.py#L10

enforced deps:
https://github.com/plotly/plotly.py/blob/master/setup.py#L279

**Comment by mmrahn** [comment]
@timkpaine Yes, but it doesn't seem to do it.

Sorry, I can't help you more because I'm not a python expert, but the example I posted would work if plotly indeed enforced it, wouldn't it?

**Comment by timkpaine** [comment]
Yep, you should raise this issue with plotly directly

**Comment by colonelchlorine** [comment]
Looks like this could be an issue up there in Plotly: https://github.com/plotly/plotly.py/issues/1111

What's strange is that I can skip cufflinks altogether and craft a Plotly graph from a Pandas DataFrame, so I just don't understand why cufflinks even needs ipywidgets to operate. Can you catch and then just skip it otherwise?

Anyone used Google Colaboratory and got this working in some way?

**Comment by timkpaine** [comment]
Could, but there are reasons to not do that, namely the JavaScript paths are different between iplot and figurewidgrt. You should raise the issue with plotly

**Comment by mahmutkocak** [comment]
In colab I have the same issue!

**Comment by liuyigh** [comment]
If you installed `ipywidgets` and still did not work, FYI, I had to **restart** ipython console for newly installed `ipywidgets` to take effect.
