### ISSUE TITLE
Annotations does not accept yref

### ISSUE THREAD

**Issue by mxlei01** [santosjorge/cufflinks#131]
I'm trying to add an annotation to one of the subplots.

But dictionary values are interpreted as key is equal to the point of x-axis to be plotted.

When I add "yref": "y3" this will print the y3 at 0,0 instead of putting the annotation at 3rd row.

```
df.iplot(vspan=vpans,
         annotations=[{df["FUP.WQ"].index[0]: "asdfasdfasdfasdfasdfasdfasdf", "yref": "y1"}], 
         subplots=True, shape=(5, 1), shared_xaxes=True)
```

![screen shot 2018-09-10 at 4 42 08 pm](https://user-images.githubusercontent.com/7399324/45328287-8e893780-b518-11e8-989d-9895d6f06b56.png)

**Comment by santosjorge** [comment]
Fixed in 0.14.2

![image](https://user-images.githubusercontent.com/2511100/45496090-904b3900-b76c-11e8-9d55-615c5a0a2485.png)
