### ISSUE TITLE
cannot upgrade to v0.14.0

### ISSUE THREAD

**Issue by lihaooooo** [santosjorge/cufflinks#133]
Trying to upgrade to v14.0 in the Terminal, but the system cannot find the newest version.
Here is what I get in the Terminal:

pip install --upgrade cufflinks==0.14.0
Collecting cufflinks==0.14.0
  Could not find a version that satisfies the requirement cufflinks==0.14.0 (from versions: 0.2, 0.3, 0.3.2, 0.4, 0.5, 0.6, 0.6.1, 0.6.3, 0.6.4, 0.6.7, 0.7.0, 0.7.1, 0.7.2, 0.8.2, 0.11.0, 0.12.0, 0.12.1, 0.13.0)
No matching distribution found for cufflinks==0.14.0

**Comment by santosjorge** [comment]
Available now on pip
