### ISSUE TITLE
logy does not get applied to each subplots

### ISSUE THREAD

**Issue by mxlei01** [santosjorge/cufflinks#134]
If you enable logy with subplots, then only the first subplot will be logy transformed.

**Comment by santosjorge** [comment]
Hi @mxlei01 -
I see this working properly. I'll use a chart with negative values to make it clearer:

![image](https://user-images.githubusercontent.com/2511100/45496709-f5535e80-b76d-11e8-8be4-226260e6a4af.png)

And applying the logy:

![image](https://user-images.githubusercontent.com/2511100/45496744-0e5c0f80-b76e-11e8-9d78-6586760a2b74.png)

Are you doing this in a different way?

**Comment by mxlei01** [comment]
Previously I have version 0.12.1, I updated to 0.14.1 and it works now.
