### ISSUE TITLE
What is cufflinks3?

### ISSUE THREAD

**Issue by dhirschfeld** [santosjorge/cufflinks#145]
How come there's a new `cufflinks3` project on [`pypi`](https://pypi.org/project/cufflinks3)?

How come `0.14.5` couldn't be published under the same `cufflinks` name?

**Comment by santosjorge** [comment]
That definitely wasn't me. I think you can see from the description that it was published by someone else. 
The latest I published on pypi was [0.14.4.](https://pypi.org/project/cufflinks/)

**Comment by santosjorge** [comment]
Seems it was published by @liudengfeng
Not very cool tbh.

**Comment by dhirschfeld** [comment]
IMO that's incredibly bad form - akin to package squatting.

![image](https://user-images.githubusercontent.com/881019/47395511-55282680-d76a-11e8-84a4-993c5f58fa25.png)


If you look carefully you can see that the maintainer isn't you but your name is still down as the author so people can be easily confused that it is an official build.

**Comment by dhirschfeld** [comment]
@santosjorge - are you happy to PM @liudengfeng to ask him to please take it down?

If he doesn't then we can appeal to @pypa to remove it.

This has happened in the past to PyPI - https://nakedsecurity.sophos.com/2017/09/19/pypi-python-repository-hit-by-typosquatting-sneak-attack/ so I'm sure they will accomodate a request to remove.

It may well not be malicious and just someone who doesn't know appropriate behaviour but either way it shouldn't be on PyPI.

**Comment by santosjorge** [comment]
@dhirschfeld completely agree. I will report it now. Thank you both for letting me know. 
@gnu-user - I'll upload 0.14.5 as well.

**Comment by santosjorge** [comment]
The extent of piracy..: https://github.com/liudengfeng/cufflinks

**Comment by timkpaine** [comment]
looks like he did it with empyrical and and pyfolio as well...

**Comment by timkpaine** [comment]
i've opened [this](https://github.com/pypa/warehouse/issues/4916) as well, it wasn't clear what the "right" thing to do is

**Comment by santosjorge** [comment]
Thank you @timkpaine for reporting it with @pypa - really appreciate the help.

**Comment by timkpaine** [comment]
this looks resolved now. I'd be wary, in some cases the copyright was removed: https://github.com/quantopian/empyrical/issues/105#issuecomment-432614197

**Comment by dhirschfeld** [comment]
Also topical - https://www.zdnet.com/google-amp/article/twelve-malicious-python-libraries-found-and-removed-from-pypi/

**Comment by dhirschfeld** [comment]
Since this seems resolved I'll close this issue...
