### ISSUE TITLE
Issue with TA-Lib 0.4.17 Installation

### ISSUE THREAD

**Issue by MaximusIndus** [santosjorge/cufflinks#153]
installing TA-Lib 0.4.17, it fails with -**^[error: command 'gcc' failed with exit status 1**

- I am on Linux hosted server (Godaddy Deluxe, which prob runs on CentOS)
- Currently installed Python 3.6.2 on virtual env. The original is 2.6.6
- I have tried instructions as shown on [this page](https://blog.csdn.net/caib1109/article/details/78119615)
- Have managed to install ta (older version of talib 0.4.0 i think - "import ta")
- I have updated the env variables with "LD_LIBRARY_PATH=./ta-lib/src/.libs/" added to it(location where I found libta_lib.so.0)
- At the beginning it gives a warning - "setup.py:79: UserWarning: Cannot find ta-lib library, installation may fail."
- And then > ".local/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION""

Any assistance would be great! @mrjbq7
Thanks.
----------------------------------------------------------------------------------
Dump>>>
fzutljptf41p@localhost [~/TA-Lib-0.4.17]$ python3 setup.py install
setup.py:79: **UserWarning: Cannot find ta-lib library, installation may fail.
  warnings.warn('Cannot find ta-lib library, installation may fail.')**
running install
^[running bdist_egg
running egg_info
writing TA_Lib.egg-info/PKG-INFO
writing dependency_links to TA_Lib.egg-info/dependency_links.txt
writing requirements to TA_Lib.egg-info/requires.txt
writing top-level names to TA_Lib.egg-info/top_level.txt
reading manifest file 'TA_Lib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'TA_Lib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
skipping 'talib/_ta_lib.c' Cython extension (up-to-date)
building 'talib._ta_lib' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/fzutljptf41p/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/home/fzutljptf41p/.local/include/python3.6m -c talib/_ta_lib.c -o build/temp.linux-x86_64-3.6/talib/_ta_lib.o
talib/_ta_lib.c:526:28: error: ta-lib/ta_defs.h: No such file or directory
talib/_ta_lib.c:527:30: error: ta-lib/ta_common.h: No such file or directory
talib/_ta_lib.c:528:32: error: ta-lib/ta_abstract.h: No such file or directory
talib/_ta_lib.c:529:28: error: ta-lib/ta_func.h: No such file or directory
In file included from /home/fzutljptf41p/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821,
                 from /home/fzutljptf41p/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/fzutljptf41p/.local/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from talib/_ta_lib.c:533:
/home/fzutljptf41p/.local/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
talib/_ta_lib.c:210099: warning: assignment from incompatible pointer type
talib/_ta_lib.c:210204: warning: assignment from incompatible pointer type
talib/_ta_lib.c:210309: warning: assignment from incompatible pointer type
talib/_ta_lib.c:210422: error: '__pyx_v_retCode' undeclared (first use in this function)
talib/_ta_lib.c:210431: error: too many arguments to function '__pyx_f_5talib_7_ta_lib__ta_check_success'
talib/_ta_lib.c: In function '__pyx_pf_5talib_7_ta_lib_668stream_WMA':
talib/_ta_lib.c:210556: error: 'TA_RetCode' undeclared (first use in this function)
talib/_ta_lib.c:210556: error: expected ';' before '__pyx_v_retCode'
talib/_ta_lib.c:210649: warning: assignment from incompatible pointer type
talib/_ta_lib.c:210698: error: '__pyx_v_retCode' undeclared (first use in this function)
talib/_ta_lib.c:210707: error: too many arguments to function '__pyx_f_5talib_7_ta_lib__ta_check_success'
^[talib/_ta_lib.c: In function 'PyInit__ta_lib':
talib/_ta_lib.c:243887: warning: implicit declaration of function 'TA_GetVersionString'
talib/_ta_lib.c:243887: warning: passing argument 1 of 'PyBytes_FromString' makes pointer from integer without a cast
/home/fzutljptf41p/.local/include/python3.6m/bytesobject.h:52: note: expected 'const char *' but argument is of type 'int'
^[talib/_ta_lib.c: At top level:
talib/_ta_lib.c:253063: error: expected ')' before 'value'
talib/_ta_lib.c:253156: error: expected ')' before 'value'
talib/_ta_lib.c:253218: error: expected ')' before 'value'
talib/_ta_lib.c:253249: error: expected ')' before 'value'
talib/_ta_lib.c:253280: error: expected ')' before 'value'
talib/_ta_lib.c:253652: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__Pyx_PyInt_As_TA_RetCode'
talib/_ta_lib.c:254030: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__Pyx_PyInt_As_TA_FuncUnstId'
talib/_ta_lib.c:254408: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__Pyx_PyInt_As_TA_CandleSettingType'
talib/_ta_lib.c:254597: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__Pyx_PyInt_As_TA_RangeType'
**^[error: command 'gcc' failed with exit status 1**

**Comment by santosjorge** [comment]
There has been a long time that cufflinks doesn't have any dependencies on TA-Lib

**Comment by TheBoy07** [comment]
Try to install these dependencies first 

windows : https://github.com/mrjbq7/ta-lib#windows 
linux : https://github.com/mrjbq7/ta-lib#linux

Solved my problem

**Comment by Ankitgelda8** [comment]
the same issue I am facing is this got resolved and how @MaximusIndus ??
