### ISSUE TITLE
hline=0 causes incorrect plot

### ISSUE THREAD

**Issue by misolietavec** [santosjorge/cufflinks#155]
__Versions__: cufflinks 0.14.6,  plotly 3.3.0

__Sample code__:
```python
import cufflinks as cf
import pandas as pd

ds = pd.DataFrame({'x':[0,1],'y':[1,-1]})
ds.iplot(hline=0,x="x",y="y")
```
results in plotting the line diagonally (from lower left to upper right corner of  plot)  instead of horizontally.
For any nonzero value (e.g.: `hline=0.0001` ) the plot is OK.

**Comment by timkpaine** [comment]
looks like the bug comes from `get_shape` which gets called

```python
from cufflinks.tools import get_shape
get_shape(x=0)
```

```
{'x0': 0,
 'y0': 0,
 'x1': 1,
 'y1': 1,
 'line': {'color': '#db4052', 'width': 1, 'dash': 'solid'},
 'xref': 'paper',
 'yref': 'paper',
 'type': 'line'}
```

**Comment by timkpaine** [comment]
@misolietavec would you mind testing https://github.com/santosjorge/cufflinks/pull/157

**Comment by misolietavec** [comment]
@timkpaine: tested, works OK for x=0

**Comment by santosjorge** [comment]
This has been now merged
