### ISSUE TITLE
secondary y-axis doesn't work with vline

### ISSUE THREAD

**Issue by jackparmer** [santosjorge/cufflinks#16]
![image](https://cloud.githubusercontent.com/assets/1865834/9426200/75d1f76e-48ff-11e5-8600-608db3d17408.png)

![image](https://cloud.githubusercontent.com/assets/1865834/9426203/86f39354-48ff-11e5-9cda-b3755e2abc43.png)

**Comment by santosjorge** [comment]
fixed
