### ISSUE TITLE
XAxis switches from dates to numbers with categories

### ISSUE THREAD

**Issue by WillKoehrsen** [santosjorge/cufflinks#160]
When making a scatterplot with a date variable on the x-axis, the axis switches to numbers (I think in milliseconds) when passing in `categories`. 

```
import pandas as pd
import cufflinks
cufflinks.go_offline()

df = pd.read_parquet(
    'https://github.com/WillKoehrsen/Data-Analysis/blob/master/plotly/data/medium_data_2019_01_06?raw=true'
)

df.iplot(kind='scatter', y='claps', x='published_date', mode='markers')

df.iplot(kind='scatter', y='claps', x='published_date', mode='markers',
             categories='publication')
```

First plot with correct dates on xaxis

![screen shot 2019-01-06 at 09 05 07 cst](https://user-images.githubusercontent.com/17484616/50737729-3b578680-1192-11e9-864d-3d93034f6766.png)

Second plot with categories and numbers on xaxis

![screen shot 2019-01-06 at 09 05 34 cst](https://user-images.githubusercontent.com/17484616/50737738-47434880-1192-11e9-8a55-c0a67fc1e020.png)

Passing in a `layout` specifying the xaxis as dates: `layout=dict(xaxis=dict(type='date'))` results in an empty plot

![screen shot 2019-01-06 at 09 09 51 cst](https://user-images.githubusercontent.com/17484616/50737808-dfd9c880-1192-11e9-8dba-732575154b58.png)

Currently, I'm trying to use a formatter for the Xaxis to convert the numbers into dates, but having issues figuring it out.

**Comment by WillKoehrsen** [comment]
Temporary solution is to use a `pivot_table`:

`df.pivot_table(values='claps', index='published_date', columns='publication').iplot(mode='markers')`

![screen shot 2019-01-06 at 09 46 19 cst](https://user-images.githubusercontent.com/17484616/50738300-f898ad00-1197-11e9-8b7e-699024c17278.png)

**Comment by santosjorge** [comment]
Looking into this.

**Comment by santosjorge** [comment]
Hi @WillKoehrsen  - Can you try this again? this should've been fixed in one of the last commits. Thank you

**Comment by santosjorge** [comment]
Here it is. 
Please reopen if you are still having issues. 

<img width="764" alt="image" src="https://user-images.githubusercontent.com/2511100/54110936-9435dc00-43da-11e9-9e4c-7d7da1674904.png">
