### ISSUE TITLE
mode='lines' shows markers, no lines when using categories

### ISSUE THREAD

**Issue by martinwk** [santosjorge/cufflinks#165]
When I use mode='lines' in a scatterplot with 'categories' option, the mode is not set correctly (it uses mode='markers'). mode='lines+markers' does give the right results. when dropping the categories option, everything works as expected

**Comment by eddy-geek** [comment]
confirmed fixed in 0.15 (which is not official yet?)

example
`tr.iplot(kind='scatter', mode='lines', x='thr', y='rat', categories='mdate')`

![image](https://user-images.githubusercontent.com/2772505/55511828-cd700d80-5661-11e9-99a4-42a38933f2fa.png)
