### ISSUE TITLE
shared_xaxes & subplots

### ISSUE THREAD

**Issue by AlaaElagha** [santosjorge/cufflinks#167]
When subplots=True, and shape(,) is not specified, subplots are displayed as a grid even when shared_xaxes=True. I would of expected it subplots would be stacked so they share the x axis. To get stacked subplots that share the x-axis, shape has to be specified, i.e. (4,1). Is this expected?

Thanks for the great library Santos.

**Comment by santosjorge** [comment]
Hi @AlaaElagha - you are right. I'll fix this now.
