### ISSUE TITLE
unable to pick up color when trying to set it from a dataframe

### ISSUE THREAD

**Issue by raggnar** [santosjorge/cufflinks#168]
Hi there,
I was trying to make cufflinks pick up color from a column and assign it to entry point when plotting
i have been unsuccessful so far and have different behaviour like xaxis change its unit or color not properly changing the example below give more detail. Can any one look into it?

Thanks

exple:
```
data = {
    'time': ['10:00:00.001001','10:00:00.020020','10:00:00.003030','10:00:00.040015','10:00:00.050025','10:00:00.060036'],
    'color': ['red','orange', 'blue', 'orange', 'orange', 'red'],
    'duration': ['0.01020642', '0.01332378', '0.01018166', '0.01882410', '0.01899997', '0.01169282']}

df = pd.DataFrame.from_dict(data)

df.time= pd.to_datetime(df.time,format='%H:%M:%S.%f')
df.duration = df.duration.astype(float)

df.iplot(kind='scatter', mode='markers', x='time', y='duration')
```
<img width="791" alt="screen shot 2019-03-03 at 2 09 06 am" src="https://user-images.githubusercontent.com/7592118/53692198-8b4d6680-3d59-11e9-9152-0179a3e49c54.png">

if i try to use categories to differentiate different color, it will messed up the xaxis
`df.iplot(kind='scatter', mode='markers', x='time', y='duration', categories='color')`
(i saw that there is a ticket fr that already

now if i use the following:

1. 

`df.iplot(kind='scatter', mode='markers', x='time', y='duration',colors='color') `
I will get 
> CufflinksError: Not a valid color: color 

2.
now if use the column color to get the color i want using 
`df.iplot(kind='scatter', mode='markers', x='time', y='duration',colors=df.color) `
i get 

> ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

3. since color can take a a value or list I then use this
`df.iplot(kind='scatter', mode='markers', x='time', y='duration',colors=df.color.tolist())`
i will get the image below

<img width="772" alt="screen shot 2019-03-03 at 2 23 36 am" src="https://user-images.githubusercontent.com/7592118/53692312-62c66c00-3d5b-11e9-966d-eeb9fa5336da.png">

the color will changed to red (first dataframe entry) but will not iterate to the list and change other entry points to their respective color

Am i doing something wrong or there is a way to achieve this (plot every single point in the dataframe with specific color)?

**Comment by raggnar** [comment]
Hey there again,

tried now using command:

`df.iplot(kind='scatter',mode='markers',symbol='circle-dot',colors=df.color.tolist(),size=10)`

got this

<img width="817" alt="screen shot 2019-03-03 at 12 51 29 pm" src="https://user-images.githubusercontent.com/7592118/53699136-19a20680-3db3-11e9-9b16-320379337609.png">

and that is not looking to what i am trying to achieve as it is not picking up the right x and y axis and the color is still not link to each entry row

**Comment by santosjorge** [comment]
This works fine to me:

```python
df.iplot(kind='scatter',x='time',y='duration',mode='markers',colors=df['color'].to_list(),categories='color')
```

<img width="770" alt="image" src="https://user-images.githubusercontent.com/2511100/53980039-39189680-4107-11e9-848a-7986b3bf1ba4.png">

**Comment by raggnar** [comment]
Hello, Thanks for looking into this but if you check the x-axis it has changed from datetime to a scientific format.
My question now is how to do it but conserve the datetime x-axis format?
regards

**Comment by santosjorge** [comment]
Ok the last commit should fix this. 

<img width="943" alt="image" src="https://user-images.githubusercontent.com/2511100/54088091-cf3ffd00-4351-11e9-8031-1f882f127c38.png">

**Comment by raggnar** [comment]
same version on Windows as well (Plotly '3.7.0' and cufflinks '0.14.6')

**Comment by raggnar** [comment]
@santosjorge

**Comment by raggnar** [comment]
Working as expected after downloading the version from Github neither pip nor pipy  have the latest.

Issue solved 

Thanks
