### ISSUE TITLE
Why does cufflinks install nose?

### ISSUE THREAD

**Issue by jhermann** [santosjorge/cufflinks#172]
Do you run tests at runtime? Otherwise please add a filter in setup.py that removes the dev-only requirements, or split those into a 2nd file.

**Comment by santosjorge** [comment]
Didn't think it was a big issue. Please feel free to propose a PR for this.

**Comment by timkpaine** [comment]
@santosjorge we should probably consider porting to nose2 or pytest in a separate issue, i dont think nose is supported anymore

**Comment by santosjorge** [comment]
No longer on the requirements
