### ISSUE TITLE
AttributeError happened when invoking subplots in plotly >= 3.8.0

### ISSUE THREAD

**Issue by happylusa-liu** [santosjorge/cufflinks#175]
When I used iplot() to draw subplots in offline like this, following AttributeError happened.
```
import cufflinks as cf
cf.go_offline()

some_pandas_data.iplot(
  subplots=True,
  shape=(len(some_pandas_data.columns), 1),
  shared_xaxes=True
)
```
```
~/envs/liu/lib/python3.7/site-packages/cufflinks/tools.py in get_subplots(rows, cols, shared_xaxes, shared_yaxes, start_cell, theme, base_layout, **kwargs)
    892 
    893         layout= base_layout if base_layout else getLayout(theme,**check_kwargs(kwargs,__LAYOUT_AXIS))
--> 894 	sp=py.plotly.tools.make_subplots(rows=rows,cols=cols,shared_xaxes=shared_xaxes,
    895                                                                                    shared_yaxes=shared_yaxes,print_grid=False,
    896 											start_cell=start_cell,**kwargs)

AttributeError: module 'chart_studio.tools' has no attribute 'make_subplots'
```

Error only happened in case of plotly >= 3.8.0. 

I think it maybe caused by this change, but I'm not sure. 
Could anyone provide any information on this? Thanks!
https://github.com/plotly/plotly.py/commit/3678aa925489b9ed429dc28863040dbb391dadb1

**Comment by grunde73** [comment]
Have exactly the same issue.

**Comment by santosjorge** [comment]
Fixed by https://github.com/santosjorge/cufflinks/pull/178

**Comment by grunde73** [comment]
Excellent, hope it is pushed to PyPi soon.

**Comment by ChristianF88** [comment]
Hi there, 

I was wondering whether the fix is released yet? At least I still got the bug, running the latest distro installed with `pip install --upgrade cufflinks`.

Thanks!!

**Comment by nitindesaiiks** [comment]
I am also getting the same issue though I have latest versions of 
plotly-3.10.0 
cufflinks-0.15

**Comment by richlysakowski** [comment]
Typical Plotly behavior ... leaving the user community high and dry for more than two year !!   

Closing the issue acting like nothing happened or it doesn't matter if you are not a paying customer is not the right approach for a commercial vendor like Plotly.  

Plotly... Either embrace and support your open source and keep it up to date, or be courteous enough to tell people you are not going to do it so they can move on to another plotting package.    Be courteous and responsible to your user base and they will respect you.  Or be irresponsible and users have a powerful right to COMPLAIN you when you waste their time with bad source code.  

THIS IS STILL AN OPEN ISSUE: 

```
plyo.iplot(
    df.iplot(kind='hist',  
             subplots=True,  
             bins=15,  
             asFigure=True),
    image='png',
    filename='ply_03'
)
```

ERROR OUTPUT:  
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-52-77a4726ece90> in <module>
      3              subplots=True,
      4              bins=15,
----> 5              asFigure=True),
      6     image='png',
      7     filename='ply_03'

c:\ProgramData\Anaconda3\lib\site-packages\cufflinks\plotlytools.py in _iplot(self, kind, data, layout, filename, sharing, title, xTitle, yTitle, zTitle, theme, colors, colorscale, fill, width, dash, mode, interpolation, symbol, size, barmode, sortbars, bargap, bargroupgap, bins, histnorm, histfunc, orientation, boxpoints, annotations, keys, bestfit, bestfit_colors, mean, mean_colors, categories, x, y, z, text, gridcolor, zerolinecolor, margin, labels, values, secondary_y, secondary_y_title, subplots, shape, error_x, error_y, error_type, locations, lon, lat, asFrame, asDates, asFigure, asImage, dimensions, asPlot, asUrl, online, **kwargs)
   1187                         else:
   1188                                 kw['subplot_titles']=kwargs['subplot_titles']
-> 1189                 figure=tools.subplots(fig,shape,base_layout=layout,theme=theme,**kw)
   1190 
   1191 

c:\ProgramData\Anaconda3\lib\site-packages\cufflinks\tools.py in subplots(figures, shape, shared_xaxes, shared_yaxes, start_cell, theme, base_layout, **kwargs)
    756                                              shared_xaxes=shared_xaxes, shared_yaxes=shared_yaxes,
    757                                              start_cell=start_cell, theme=theme,base_layout=base_layout,
--> 758 				             **kwargs)
    759         list_ref=(col for row in grid_ref for col in row)
    760         for i in range(len(figures)):

c:\ProgramData\Anaconda3\lib\site-packages\cufflinks\tools.py in get_subplots(rows, cols, shared_xaxes, shared_yaxes, start_cell, theme, base_layout, **kwargs)
    885 
    886         layout= base_layout if base_layout else getLayout(theme,**check_kwargs(kwargs,__LAYOUT_AXIS))
--> 887 	sp=py.plotly.tools.make_subplots(rows=rows,cols=cols,shared_xaxes=shared_xaxes,
    888                                                                                    shared_yaxes=shared_yaxes,print_grid=False,
    889 											start_cell=start_cell,**kwargs)

AttributeError: module 'chart_studio.tools' has no attribute 'make_subplots'


```

**Comment by santosjorge** [comment]
Just to make it clear - this is an independent library, it is not supported by Plotly.

**Comment by richlysakowski** [comment]
Hi  Jorge,

Thank you for responding so fast.

Which is the right support forum to report this cufflinks / plotly issue?
 Plotly has leveraged this library for several years and embedded it in
their open source library and their commercial product library.   I want to
report this issue so that they adequately support and fix issues like this
in a timely manner.    I have the experience that they don't regularly scan
public forums like github to fix problems with older releases of their
Plotly and Dash software.

Where would you suggest I report this issue so that Plotly corporation
addresses it and fixes it?

Thank you.

Best Regards,

Rich Lysakowski, Ph.D.
Data Scientist, Analytics Engineer,
and Senior Business Analyst
781-640-2048 mobile

**Comment by santosjorge** [comment]
It looks like plotly/chart-studio removed the make-subplots method on their latest chart studio update. I’ll look into it.
