### ISSUE TITLE
multiple chart types?

### ISSUE THREAD

**Issue by chriddyp** [santosjorge/cufflinks#18]
hey @santosjorge - thoughts on the best way to plot multiple chart types, i.e. a `bar` and a `line`?

`type` as an `array` or a `dict`, sort of like how `secondary_y` works:
```
df = pd.DataFrame({
     'y1': [3, 1, 5], 
     'y2': [30, 50, 20]
}, index=[1, 2, 3])

df.iplot(kind={'y1': 'bar', 'y2': 'scatter'})

df.iplot(kind=['bar', 'scatter'])
```

this pattern could apply to any of the non-array figure properties, e.g.

```
df.iplot(mode=['markers', 'text'], marker=[{'color': 'blue}, {'color': 'red'}])
```

**Comment by santosjorge** [comment]
Hey Chris, 

Currently the way to do this would be:

```python
fig=cf.tools.figures(df,[{'kind':'bar'},{'kind':'scatter','mode':'markers','color':'red'}])
cf.iplot(fig)
```
**cf.tools.figures** takes a DataFrame and then a list of dictionaries with all the specs. 

This works today. But of course it could be enhanced if you think it could be made easier. I think passing the 'kind' types in a dict is intuitive enough, the problem is when you start passing specs. That is why I went down this way, but let me know what you think.

**Comment by chriddyp** [comment]
got it! that looks like a good solution for now!

**Comment by chriddyp** [comment]
hey @santosjorge - I'm just giving this a try today. Since `cf.tools.figures` returns a list of `figures`, it seems like I need to merge the figures before I plot them, e.g.

```
df = cf.datagen.lines(2, 5)

figs = cf.tools.figures(df, [
    {'kind': 'bar'},
    {'kind': 'scatter', 'mode': 'markers'}
])

fig = {'data': [], 'layout': {}}
for f in figs:
    fig['data'].extend(f['data'])
    fig['layout'].update(f['layout'])
```

I'm not sure if the solution is for `cf.tools.figures` to return a single, merged figure or for another `cf.tools` function like `cf.tools.create_figure`, or the original suggestion of letting `df.iplot` accept values as an array. Thoughts?

**Comment by santosjorge** [comment]
Hey Chris, 
cf.figures returns a single figure already merged. You should be able to do 

```python
df = cf.datagen.lines(2, 5)

figs = cf.tools.figures(df, [
    {'kind': 'bar'},
    {'kind': 'scatter', 'mode': 'markers'}
])

cf.iplot(figs)
```
without any issue. 

But I'll work in a new function to do accept values as an array. I will try first with `df.iplot`, I am just concerned about overloading it too much. I'll get back to you on this.

**Comment by RubenPhy** [comment]
Hi.
I am trying to have different kind of plots with different data and with a secondary axis. But in the last step of having a different axis I have had problems. How I could solve this step?
I try adding a secondary y axis, but it doesn't work.

```
df = pd.DataFrame({'y1': [3, 1, 5], 'y2': [30, 50, 20], 'y3': [300, 500, 200]}, index=[1, 2, 3])
fig=cf.tools.figures(df,[{'kind':'bar','keys':['y2','y1']},
                         {'kind':'scatter','keys':['y3'],'mode':'markers','color':'red',
                         'secondary_y':['y3']}])
```

Version '0.17.0'
Thank you so much in advance.
