### ISSUE TITLE
Can't plot datetime when using 'categories' option in scatter

### ISSUE THREAD

**Issue by shahab-ai** [santosjorge/cufflinks#182]
When using 'categories' option with kind='scatter', the axis with datetime values would only show numbers. Below is an example code and the output:

```
import pandas as pd
import numpy as np
import cufflinks as cf
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)
cf.go_offline()
cf.set_config_file(theme='pearl')

df = pd.DataFrame({'x': np.arange(100)*10., 'y':np.sin(np.arange(100)/10), 'z':np.floor(np.arange(100)/10)})
df.x = pd.to_timedelta(df.x, unit='s') + pd.Timestamp.now()
df.z = df.z.astype('category')
df.iplot(x='x', y='y', categories='z')
```
![newplot](https://user-images.githubusercontent.com/16964895/57954752-afc0d580-78a8-11e9-8a1c-3791303b1e24.png)

**Comment by santosjorge** [comment]
Hi @shahab-ai , can you please confirm which version of Cufflinks are you using? I am seeing this just fine on v 0.15

![image](https://user-images.githubusercontent.com/2511100/58209994-177b8400-7ce0-11e9-84f0-470ad1866a3b.png)

**Comment by shahab-ai** [comment]
Hi @santosjorge , I am using version '0.14.6'. I'll go ahead and update it.

Thanks
