### ISSUE TITLE
cufflinks support for plotly 4 (offline only package ie. plotly)

### ISSUE THREAD

**Issue by kevbroch** [santosjorge/cufflinks#196]
For background here's [Medium article](https://medium.com/@plotlygraphs/plotly-py-4-0-is-here-offline-only-express-first-displayable-anywhere-fc444e5659ee) on major changes with plotly.

> Starting with this version, the only supported mode of operation in the plotly package is “offline” mode, which requires no internet connection, no account, no authentication tokens, and no payment of any kind. Support for “online” mode has been moved into a separately-installed package called chart-studio.

Although I have seen solutions in issues here with regards to using chart-studio (instead of plotly==4.0), I wanted to make the request for support for the new offline only plotly==4.0 package.

**Comment by nicolaskruchten** [comment]
Ill get a PR in next week to address this! Soon as I’m back from vacation :)

**Comment by ecederstrand** [comment]
I tried to run the test suite on PR #198 against plotly 4.1.0 but lots of test cases regarding subplots are failing. I jumped into the failing code but I failed to find out what's going on in  the /cufflinks/tools.py:subplots` method. Cufflinks relies on a private `_grid_ref` attribute that has substantially changed in plotly 4.1.0.

**Comment by nicolaskruchten** [comment]
Yeah, I'm partway through dealing with the subplots issues... taking longer than planned, clearly :)

**Comment by ecederstrand** [comment]
Hi @nicolaskruchten Eagerly awaiting news on this issue :-) Is there anything I can do to help?

**Comment by nicolaskruchten** [comment]
@ecederstrand and others: I'm still intending to work on this, it's just hard to find the time :)

**Comment by nicolaskruchten** [comment]
Fixed in #202 !
