### ISSUE TITLE
Unable to import cufflinks; importerror no module named 'plotlytools'

### ISSUE THREAD

**Issue by BlackArbsCEO** [santosjorge/cufflinks#2]
Hi,

When I try to import the cufflinks library into my Python environment I'm getting an ImportError.

My environment:
Windows 8.1 64bit
WinPython 64bit running Python 3.4.3

From what I can see all the files are structured correctly in the proper WinPython environment. Any ideas what could be causing the issue? 

![cufflinks_importerror](https://cloud.githubusercontent.com/assets/7452471/6921540/c8010064-d782-11e4-942f-e5758e3a6633.png)

**Comment by santosjorge** [comment]
Hello - 
At the moment Cufflinks is only supported on Python 2.7.
I saw you were able to come up with a workaround which you posted on http://stackoverflow.com/questions/29401260/importerror-no-module-named-plotlytools-when-importing-cufflinks
This should be enough for it to run on Python 3.x

Thank you for raising this issue. I will try to address support for Python 3.x in the coming versions. 
Meanwhile do not upgrade to Cufflinks 0.3 as you will need to go through all these fixes again. 
I will leave this issue open until this has been addressed.

Thank you,
Jorge

**Comment by chriddyp** [comment]
@santosjorge - we wrote some great functionality in our automated circleci tests that automates these tests against all python versions: https://github.com/plotly/python-api/blob/master/circle.yml

**Comment by santosjorge** [comment]
Version 0.7.0 supports Python 3

**Comment by ingfitz** [comment]
Any news when Cufflinks is going to be supported on Python 3.x?

![screen shot 2017-07-03 at 4 21 52 pm](https://user-images.githubusercontent.com/20709401/27806990-ed91aefa-600b-11e7-8b8c-db2029185e05.jpg)
