### ISSUE TITLE
cufflink import failure

### ISSUE THREAD

**Issue by Swapnadeep1998** [santosjorge/cufflinks#209]
![problem](https://user-images.githubusercontent.com/56325443/67513662-eb15ca80-f6b8-11e9-851c-c3a6f3c0d357.png)

how to fix it?

**Comment by nicolaskruchten** [comment]
This is because the current version of Cufflinks is incompatible with Plotly v4+. The next version of Cufflinks (should be out soon!) will resolve this. In the meantime, you can downgrade to Plotly v3.10.0

**Comment by Swapnadeep1998** [comment]
> This is because the current version of Cufflinks is incompatible with Plotly v4+. The next version of Cufflinks (should be out soon!) will resolve this. In the meantime, you can downgrade to Plotly v3.10.0

Thank you so much, understood the problem and resolved it.
