### ISSUE TITLE
pie chart subplots

### ISSUE THREAD

**Issue by chriddyp** [santosjorge/cufflinks#21]
pie chart subplots are created slightly differently than cartesion subplots - they use the `domain` property inside the traces. Here is an example: https://plot.ly/python/pie-charts/#pie-chart-subplots

would be cool if this were supported. my attempt was something along the lines of:

```
cf.tools.subplots([df.iplot(kind='pie', labels='a', values=c, asFigure=True) for c in ['a', 'b', 'c', 'd']])
```

**Comment by santosjorge** [comment]
You can now try

```python
pies=[cf.datagen.pie().figure(kind='pie',values='values',labels='labels') for _ in list(range(4))]
cf.iplot(cf.subplots(pies))
```

**Comment by PanWu** [comment]
I just tried this command, and seems like the error still persist. (version 0.8.2). Is this issue be resolved? 
<img width="1007" alt="screen shot 2016-10-30 at 11 24 38 pm" src="https://cloud.githubusercontent.com/assets/7094433/19845859/173104a2-9ef8-11e6-8eb7-4607e942aea1.png">
