### ISSUE TITLE
mouseover for values in area iplot only shows one value (where it use to show all in the same x previously in v0.16.0)

### ISSUE THREAD

**Issue by kevbroch** [santosjorge/cufflinks#212]
I noticed a change in behavior when I upgraded to cufflinks 0.17.0 .  Wondering if this is an issue or expected change in behavior?  By the looks of [plotly docs](https://plot.ly/python/filled-area-plots/) it looks like new behavior.

Previously I would see all the y values when I moused over a given x value, now I only see one.  Also the x value is now grouped with the y value rather than being it's own highlight on x axis.

Images below should make this clear:

Before (v0.16.0 and plotly v3.10.0) : 
![good_stacked](https://user-images.githubusercontent.com/176243/67705347-15df7780-f974-11e9-9302-c0da0f60945f.png)

After (v.0.17.0 and plotly v4.2.1):
![onlyone_stacked](https://user-images.githubusercontent.com/176243/67705363-1bd55880-f974-11e9-96f8-a5b978bd95db.png)

**Comment by timkpaine** [comment]
Are you sure this is a cufflinks issue and not a changed plotly behavior?

**Comment by kevbroch** [comment]
Agreed: https://plot.ly/python/reference/#scatter-hoverinfo

I guess what I'd like is plotly to have an `hoverinfo="ally"` (meaning all Y trace values)

**Comment by nicolaskruchten** [comment]
@timkpaine is right: the new default Plotly settings are to have `hovermode: "closest"`.

@santosjorge I forgot that there is a new Plotly.py default template which changes a bunch of settings like this. We should probably roll out a 0.17.1 that suppresses this, for people who really do want minimal changes. Sorry I missed this!

Basically we need to set `layout.template ="none"` to clear out the new defaults
