### ISSUE TITLE
plotting from command line

### ISSUE THREAD

**Issue by nateGeorge** [santosjorge/cufflinks#215]
Does anyone else have the problem of iplot not working well from the command line?  When I want to plot something from IPython for example, I run something like `df.iplot()`.  This executes, but nothing shows up.  The way around it has been:

```python
# ensure plotly/cufflinks plots to browser
# cufflinks must be imported AFTER this
import plotly.io as pio
pio.renderers.default = "browser"
import cufflinks as cf

df.iplot()
```

**Comment by nateGeorge** [comment]
Ok, there are a few ways to do this (although some things seem buggy).

```python
# opens as a plot.ly plot on their site, unless you do cf.go_offline()
df.iplot(asPlot=True)

# this should show the image, but doesn't
df.iplot(asImage=True, display_image=True)
```

**Comment by nicolaskruchten** [comment]
@nateGeorge when you say "plotting from the command line" you mean in a regular terminal with a regular `python` shell, or in `ipython` in a terminal, or in VSCode or PyCharm or Spyder or... ?

**Comment by nateGeorge** [comment]
I used IPython actually.

**Comment by nicolaskruchten** [comment]
OK so here's whats happening:

1. IPython in a terminal can't display images inline in general: it always needs to defer to some external system to open a window to render an image, so `asImage` isn't going to do anything there. This isn't a bug so much as a limitation of the terminal :)
2. Cufflinks wraps `plotly` and `chart_studio` as "offline" and "online" modes
3. In "offline" mode this means you'll use the renderer framework from `plotly`, and setting the default renderer to `browser` will get you a browser window with a plot in it, all locally-hosted
4. In "online" mode you'll upload your chart to Chart Studio Cloud and pop open a browser window that displays that.

If you don't want to set the default renderer in offline mode, you can use something like `df.iplot(asFigure=True).show("browser")` or `df.figure().show("browser")`

**Comment by nateGeorge** [comment]
Awesome, thanks, much appreciated.
