### ISSUE TITLE
import cufflinks after Mac update to 10.15.1

### ISSUE THREAD

**Issue by cchuang2009** [santosjorge/cufflinks#217]
While updating to the last Mac system, 
“import cufflinks” always broke the Jupyter notebook and pyhon env as follows:

>>> import cufflinks
Segmentation fault: 11

I use

python 3.6
plotly: 4.2.1
graph_studio:1.0
cufflinks: 0.17

**Comment by eholic** [comment]
@cchuang2009  Do you still have the issue? In my following environment, it works fine.

|Package|ver.|
|-|-|
|macOS Catalina | 10.15.1|
|jupyter|4.4.0|
|Python| 3.6.5|
|plotly| 4.2.1|
|cufflinks| 0.17.0|

**Comment by cchuang2009** [comment]
This problem was solved after updating pandas from 0.25.1 to 0.25.3.

Thanks,

**Comment by cchuang2009** [comment]
problem was solved after updating pandas from 0.25.1 to 0.25.3.

Thanks,

cch
