### ISSUE TITLE
Generate ohlc chart but get an attribute error?

### ISSUE THREAD

**Issue by steveycchen** [santosjorge/cufflinks#227]
Hi, I am new to cufflinks and want to generate an ohlc chart from yahoo finance data. I got an AttributeError: 'DataFrame' object has no attribute 'ix' in qf.iplot(). 
Any advice is highly appreciated! Thank you!

`import pandas as pd 
import pandas_datareader.data as pdr 
import chart_studio.plotly as py
import plotly.graph_objs as go
from plotly.offline import iplot,init_notebook_mode
import cufflinks as cf 
cf.go_offline(connected=True)
init_notebook_mode(connected=True)

# Get data from yahoo and reanme the columns
df = pdr.DataReader("gs", 'yahoo', datetime(2019, 1, 1), datetime(2019, 12, 28))
df.rename(columns={'High': 'high', 'Low': 'low', 'Open': 'open', 'Close': 'close','Volume': 'volume'}, inplace=True)
df = df[['high','low','open','close','volume']]

# Generate the ohlc chart but with errors -> AttributeError: 'DataFrame' object has no attribute 'ix'
df=cf.datagen.ohlc()
qf=cf.QuantFig(df,title='First Quant Figure',legend='top',name='GS')
qf.add_bollinger_bands()
qf.iplot()`

**Comment by santosjorge** [comment]
Hi @steveycchen  - can you paste the whole error you are getting? 

This seems to work just fine

```python 
import cufflinks as cf
df=cf.datagen.ohlc()
qf=cf.QuantFig(df,title='First Quant Figure',legend='top',name='GS')
qf.add_bollinger_bands()
qf.iplot()
```

![image](https://user-images.githubusercontent.com/2511100/74134254-1974d280-4be2-11ea-9a9b-1f06ff7c0d37.png)

**Comment by steveycchen** [comment]
Hi santosjorge,

Thanks for the reply!
As I run the code you post, I got the same errors from my site as below.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-c04d9a425c34> in <module>
      3 qf=cf.QuantFig(df,title='First Quant Figure',legend='top',name='GS')
      4 qf.add_bollinger_bands()
----> 5 qf.iplot()

~/miniconda3/envs/dashenv/lib/python3.6/site-packages/cufflinks/quant_figure.py in iplot(self, **kwargs)
   1163 
   1164                 d=self_kwargs
-> 1165                 df=self._get_sliced(_slice).copy()
   1166                 if _resample:
   1167                         if utils.is_list(_resample):

~/miniconda3/envs/dashenv/lib/python3.6/site-packages/cufflinks/quant_figure.py in _get_sliced(self, slice, df)
    147                 a=None if a in ('',None) else utils.make_string(a)
    148                 b=None if b in ('',None) else utils.make_string(b)
--> 149                 return df.ix[a:b]
    150 
    151         def _get_resampled(self,rule,how={'ohlc':'last','volume':'sum'},df=None,**kwargs):

~/miniconda3/envs/dashenv/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5271             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5272                 return self[name]
-> 5273             return object.__getattribute__(self, name)
   5274 
   5275     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'ix'

**Comment by santosjorge** [comment]
I believe you are using an old version. All the .ix reference were updated some time ago. Can you check which version you are using?

**Comment by steveycchen** [comment]
I check my installed package in env, which is version of 0.17. If this is not the latest one, would you goide me how to update or reinstall? I am using mini conda and python 3.6 in mac. Thank you!

**Comment by steveycchen** [comment]
Hi Jorge, 
I checked my installed packages, which showed me the installed cufflinks version is 0.17.
# packages in environment at /Users/steve/miniconda3/envs/dashenv:
#
# Name                    Version                   Build  Channel
cufflinks-py              0.17.0                     py_1    conda-forge

Is 0.17 the latest version?  Your further guidance and comments are highly appreciated! Thank you!

**Comment by santosjorge** [comment]
You should be able to update it with 
```
pip install cufflinks -U

**Comment by steveycchen** [comment]
Hi Jorge, 
Thanks for the reply and instruction!
I tried to upgrade cufflinks by using "pip install cufflinks -U" but it showed me that all requirements were satisfied. Everything seems back to the original point. Below are the messages from my console.

(dashenv) ➜  ~ pip install cufflinks -U
Requirement already up-to-date: cufflinks in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (0.17.0)
Requirement already satisfied, skipping upgrade: ipython>=5.3.0 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from cufflinks) (7.12.0)
Requirement already satisfied, skipping upgrade: numpy>=1.9.2 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from cufflinks) (1.18.1)
Requirement already satisfied, skipping upgrade: pandas>=0.19.2 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from cufflinks) (1.0.0)
Requirement already satisfied, skipping upgrade: ipywidgets>=7.0.0 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from cufflinks) (7.5.1)
Requirement already satisfied, skipping upgrade: plotly>=4.1.1 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from cufflinks) (4.4.1)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from cufflinks) (1.14.0)
Requirement already satisfied, skipping upgrade: colorlover>=0.2.1 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from cufflinks) (0.3.0)
Requirement already satisfied, skipping upgrade: chart-studio>=1.0.0 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from cufflinks) (1.0.0)
Requirement already satisfied, skipping upgrade: setuptools>=34.4.1 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from cufflinks) (45.1.0.post20200127)
Requirement already satisfied, skipping upgrade: pexpect; sys_platform != "win32" in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipython>=5.3.0->cufflinks) (4.8.0)
Requirement already satisfied, skipping upgrade: appnope; sys_platform == "darwin" in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipython>=5.3.0->cufflinks) (0.1.0)
Requirement already satisfied, skipping upgrade: pickleshare in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipython>=5.3.0->cufflinks) (0.7.5)
Requirement already satisfied, skipping upgrade: jedi>=0.10 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipython>=5.3.0->cufflinks) (0.16.0)
Requirement already satisfied, skipping upgrade: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipython>=5.3.0->cufflinks) (3.0.3)
Requirement already satisfied, skipping upgrade: decorator in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipython>=5.3.0->cufflinks) (4.4.1)
Requirement already satisfied, skipping upgrade: pygments in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipython>=5.3.0->cufflinks) (2.5.2)
Requirement already satisfied, skipping upgrade: backcall in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipython>=5.3.0->cufflinks) (0.1.0)
Requirement already satisfied, skipping upgrade: traitlets>=4.2 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipython>=5.3.0->cufflinks) (4.3.3)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from pandas>=0.19.2->cufflinks) (2019.3)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from pandas>=0.19.2->cufflinks) (2.8.1)
Requirement already satisfied, skipping upgrade: widgetsnbextension~=3.5.0 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipywidgets>=7.0.0->cufflinks) (3.5.1)
Requirement already satisfied, skipping upgrade: nbformat>=4.2.0 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipywidgets>=7.0.0->cufflinks) (5.0.4)
Requirement already satisfied, skipping upgrade: ipykernel>=4.5.1 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipywidgets>=7.0.0->cufflinks) (5.1.4)
Requirement already satisfied, skipping upgrade: retrying>=1.3.3 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from plotly>=4.1.1->cufflinks) (1.3.3)
Requirement already satisfied, skipping upgrade: requests in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from chart-studio>=1.0.0->cufflinks) (2.22.0)
Requirement already satisfied, skipping upgrade: ptyprocess>=0.5 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from pexpect; sys_platform != "win32"->ipython>=5.3.0->cufflinks) (0.6.0)
Requirement already satisfied, skipping upgrade: parso>=0.5.2 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from jedi>=0.10->ipython>=5.3.0->cufflinks) (0.6.1)
Requirement already satisfied, skipping upgrade: wcwidth in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->cufflinks) (0.1.8)
Requirement already satisfied, skipping upgrade: ipython-genutils in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from traitlets>=4.2->ipython>=5.3.0->cufflinks) (0.2.0)
Requirement already satisfied, skipping upgrade: notebook>=4.4.1 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (6.0.3)
Requirement already satisfied, skipping upgrade: jsonschema!=2.5.0,>=2.4 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (3.2.0)
Requirement already satisfied, skipping upgrade: jupyter-core in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (4.6.1)
Requirement already satisfied, skipping upgrade: jupyter-client in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (5.3.4)
Requirement already satisfied, skipping upgrade: tornado>=4.2 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (6.0.3)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from requests->chart-studio>=1.0.0->cufflinks) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from requests->chart-studio>=1.0.0->cufflinks) (2.8)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from requests->chart-studio>=1.0.0->cufflinks) (2019.11.28)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from requests->chart-studio>=1.0.0->cufflinks) (1.25.8)
Requirement already satisfied, skipping upgrade: nbconvert in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (5.6.1)
Requirement already satisfied, skipping upgrade: pyzmq>=17 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (18.1.1)
Requirement already satisfied, skipping upgrade: prometheus-client in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.7.1)
Requirement already satisfied, skipping upgrade: terminado>=0.8.1 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.8.3)
Requirement already satisfied, skipping upgrade: jinja2 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (2.10.3)
Requirement already satisfied, skipping upgrade: Send2Trash in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.5.0)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (19.3.0)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (1.5.0)
Requirement already satisfied, skipping upgrade: pyrsistent>=0.14.0 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (0.15.7)
Requirement already satisfied, skipping upgrade: testpath in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.4.4)
Requirement already satisfied, skipping upgrade: defusedxml in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.6.0)
Requirement already satisfied, skipping upgrade: bleach in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (3.1.0)
Requirement already satisfied, skipping upgrade: pandocfilters>=1.4.1 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.4.2)
Requirement already satisfied, skipping upgrade: mistune<2,>=0.8.1 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.8.4)
Requirement already satisfied, skipping upgrade: entrypoints>=0.2.2 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.3)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.1.1)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (2.1.0)
Requirement already satisfied, skipping upgrade: webencodings in ./miniconda3/envs/dashenv/lib/python3.6/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.5.1)
(dashenv) ➜  ~

**Comment by hoishing** [comment]
I got the same problem. I have cufflinks 0.17.0 installed. Its the latest version available in pypi now. 

btw. I just download the source code from git, its 0.17.2 and works fine.

@santosjorge probably pypi need to be updated :)

**Comment by steveycchen** [comment]
Thanks Kevin! Yes, the problem solved after replace the new .py files on git.

**Comment by santosjorge** [comment]
PyPi has now been updated with 0.17.3
