### ISSUE TITLE
Multiple Chart Type in one Graph

### ISSUE THREAD

**Issue by Anuj180** [santosjorge/cufflinks#231]
df = pd.DataFrame({
     'y1': [3, 1, 5], 
     'y2': [30, 50, 20]
}, index=[1, 2, 3])

is this possible that I can plot 'y1' as a Scatter chart and 'y2' as a line chart in one picture?

Currently using :

fig=cf.tools.figures(df,[{'kind':'bar'},{'kind':'scatter','mode':'markers','color':'red'}])
cf.iplot(fig)

 but not working

**Comment by santosjorge** [comment]
You can try the following

```python
fig=cf.tools.merge_figures([df['y1'].figure(kind='lines',width=3),df['y2'].figure(kind='bar',color='red')])
cf.iplot(fig)
```

![image](https://user-images.githubusercontent.com/2511100/75629911-2af83b80-5bde-11ea-9741-31d78934480c.png)

**Comment by santosjorge** [comment]
As per above
