### ISSUE TITLE
'Line' Not Allowed in Histogram

### ISSUE THREAD

**Issue by NArtin** [santosjorge/cufflinks#25]
I'm following the cufflinks tutorials on plotly word for word and anytime I try to make a histogram, including dataframe scatter matrices, I get the following error:

    PlotlyDictKeyError: 'line' is not allowed in 'histogram'

    Path To Error: ['line']

    Valid attributes for 'histogram' at path [] under parents []:

        ['dx', 'orientation', 'stream', 'zsrc', 'ysrc', 'xbins', 'xsrc',
        'visible', 'marker', 'y0', 'tsrc', 'uid', 'showlegend', 'error_x',
        'error_y', 'rsrc', 'xaxis', 'text', 'bardir', 'type', 'opacity',
        'legendgroup', 'nbinsx', 'nbinsy', 'textsrc', 'histfunc', 'hoverinfo',
        'x0', 'ybins', 'autobiny', 'autobinx', 'name', 'yaxis', 'dy',
        'histnorm', 'r', 't', 'y', 'x', 'z']

I tried reinstalling cufflinks (successfully), to no avail. Any ideas?

This is the code I'm using:

    import plotly.plotly as py
    import cufflinks as cf
    import pandas as pd
    import numpy as np

    df = pd.DataFrame(np.random.randn(1000, 4), columns=['a', 'b', 'c', 'd'])
    df.scatter_matrix(filename='cufflinks/scatter-matrix', world_readable=True)

and...

    df = pd.DataFrame({'a': np.random.randn(1000) + 1,
                       'b': np.random.randn(1000),
                       'c': np.random.randn(1000) - 1})
    df.iplot(kind='histogram', filename='cufflinks/basic-histogram')

(Sorry if this is an inappropriate place to ask this question, if it is, please direct me to somehwere more appropriate and I'll ask it there.)

**Comment by santosjorge** [comment]
Hi @NArtin , this was actually fixed in https://github.com/santosjorge/cufflinks/pull/22
Would it be possible to clone the latest version available and try it again? 
This has not been updated on pypi, so would need to be done directly from the github repo. 
Any issues let me know.

**Comment by santosjorge** [comment]
The above example works fine with the latest version

**Comment by NArtin** [comment]
Thanks for the suggestion I will try it out later today.

**Comment by NArtin** [comment]
Worked perfectly, thanks.
