### ISSUE TITLE
VSpan argument incompatiable with plotly.graph_objs.Layout

### ISSUE THREAD

**Issue by jackgolding** [santosjorge/cufflinks#26]
Thanks for providing us with an awesome library!

When I try to call

    import pandas as pd
    import cufflinks as cf
    import plotly.graph_objs as go

    x.iplot(world_readable=False, filename='test/test',
                              vspan = [{
                                'x0': '2015-01-01', 'x1': '2015-12-31',
                                'color': 'teal', 'fill': True, 'opacity': .4}],
                              layout=go.Layout(title='title',
                                xaxis1=dict(title='date',tickfont=dict(size=18)),
                                yaxis1=dict(title='y',range=[0,100],tickfont=dict(size=18))))

It seems that the vspan argument is ignored. I have tried to use shapes as an argument with go.Layout, however its actually go.Scatter(layout) that can use the shapes parameter, not go.Layout. Any ideas on how to include both a vspan and a layout object?

Cheers,

Jack

**Comment by santosjorge** [comment]
You can try now
```python
x.iplot(world_readable=False, filename='test/test',
                          vspan = [{
                            'x0': '2015-01-01', 'x1': '2015-12-31',
                            'color': 'teal', 'fill': True, 'opacity': .4}],
                          layout_update=go.Layout(title='title',
                            xaxis1=dict(title='date',tickfont=dict(size=18)),
                            yaxis1=dict(title='y',range=[0,100],tickfont=dict(size=18))))
```

**Comment by jackgolding** [comment]
Thank you!
