### ISSUE TITLE
Cufflinks is installed in Anaconda,But it says No module named 'cufflinks'

### ISSUE THREAD

**Issue by harioyyoth** [santosjorge/cufflinks#262]
Dear Team,

I installed cufflinks in my Anaconda environment. Done as per the instructions present on the Anaconda website. In Anaconda navigator it is showing Cufflinks as installed. But when I run the code it says no module present. Could you please help me to solve this issue?
![Cufflinks_Conda](https://user-images.githubusercontent.com/70841291/118927779-eb8f4980-b95f-11eb-8031-34a0f4e26a8d.png)
![After Running the code](https://user-images.githubusercontent.com/70841291/118927790-ee8a3a00-b95f-11eb-9087-83304e0622b5.png)

Regards
HARI

**Comment by santosjorge** [comment]
Hi @harioyyoth - I have not published this in Anaconda yet - so not sure if someone published a fork
