### ISSUE TITLE
showing multiple small graphs in a notebook cell output

### ISSUE THREAD

**Issue by cailiang9** [santosjorge/cufflinks#27]
For example: assume each row can show 3 figures (maybe we can also adjust the number for very big displays), the output could be:

fig0 fig1 fig2
fig3 fig4 fig5
fig6 ...

when we click a figure, it can expand to 100% in width.

This is very important for dense experiment work, such as CNN (Deep learning). We can plot neuron weights for many neurons (a heatmap for each neuron) easily. And we don't lose global views.

We don't use subplot because it needs to determine the numbers first and we need to hold the handle of a panel. (We don't like too much intrusive code in the framework for assist purpose)

Do you think it can be integrated in cufflinks?

**Comment by santosjorge** [comment]
Hi @cailiang9 - This would be more an enhancement for plotly on their javascript file. If they can support these kind of visualisations/interactions they surely we can add it to cufflinks as well.
