### ISSUE TITLE
Javascript error in jupyter on cufflinks Import

### ISSUE THREAD

**Issue by akansal1** [santosjorge/cufflinks#31]
I am using datepicker widget given in Ipywidgets example along with plotly, Whenever I import cufflinks for plotting I start to get following javascript error: TypeError: require is not a function

**Comment by djchou** [comment]
Do you have this problem when you use plotly and the datepicker widget without cufflinks?  I had a similar problem when using qgrid and plotly together and there was a javascript conflict in the underlying libraries.  I've read that the datepicker widget and plotly might have the same conflict.  

Unfortunately, my problem has not been resolved yet so i'm not sure if there is a resolution for this one either.

**Comment by djchou** [comment]
It looks like this issue will soon be resolved.

https://github.com/plotly/plotly.py/issues/408

**Comment by akansal1** [comment]
Actually, it just got resolved yesterday plotly/plotly.py/pull/412

I have not tested it yet, though...
