### ISSUE TITLE
cufflinks go_offline() and latex

### ISSUE THREAD

**Issue by jcrichard** [santosjorge/cufflinks#32]
Hi,

When I use go_offline() my latex formula on ipython stay on the left and are not centered. Any idea why ?

Thanks

**Comment by santosjorge** [comment]
Hello, this should be raised to Plotly themselves. Even when not using cufflinks, the following

```python
import plotly
plotly.offline.init_notebook_mode()
```

Will result in all latex formula to be left aligned.
