### ISSUE TITLE
dimensions arg not propogated to .getLayout method

### ISSUE THREAD

**Issue by nehalecky** [santosjorge/cufflinks#33]
Hi @santosjorge,

Thanks for the great library. Since plot.ly has been open sourced, I've been using cufflinks all the time to great fanfare. Kudos.

It seems that the `dimensions` argument in an `.iplot` call isn't passed through to the subsequent `.getLayout` method in generation of a [plotly Layout object with defined height and widths](https://plot.ly/python/setting-graph-size/). This prevents creating a Plotly visualization when working interactively (e.g., offline in Jupyter notebook). Is this by design / intentional?

Minimal working example, demonstrating the resultant `Layout` dict repr not containing `height` or `width`. 

```python
In [1]:  import cufflinks as cf
In [2]: cf.datagen.lines().iplot(asFigure=True, dimensions=(500, 500)).layout

{ 'legend': {'bgcolor': '#F5F6F9', 'font': {'color': '#4D5663'}},
 'paper_bgcolor': '#F5F6F9',
 'plot_bgcolor': '#F5F6F9',
 'titlefont': {'color': '#4D5663'},
 'xaxis1': {'gridcolor': '#E1E5ED',
  'showgrid': True,
  'tickfont': {'color': '#4D5663'},
  'title': '',
  'titlefont': {'color': '#4D5663'},
  'zerolinecolor': '#E1E5ED'},
 'yaxis1': {'gridcolor': '#E1E5ED',
  'showgrid': True,
  'tickfont': {'color': '#4D5663'},
  'title': '',
  'titlefont': {'color': '#4D5663'},
  'zerolinecolor': '#E1E5ED'}}
```

I have a quick fix for this (if it is indeed an issue), and will submit a PR shortly—thanks! :)

**Comment by santosjorge** [comment]
Thanks for the PR!
