### ISSUE TITLE
Chart Dimensions config

### ISSUE THREAD

**Issue by djchou** [santosjorge/cufflinks#36]
Is there a way to set a default chart dimension?  Currently, the charts default to a size that exceeds my cell output window so all charts have a horizontal scroll bar.  I've gotten around it by using dimensions  but was wondering if it was possible to have the dimensions set by default.

**Comment by Fractally** [comment]
I also have this issue. Why does the dimensions have to be fixed? I would like to embed the generated figures into HTML iframe components that can have different sizes depending on the web browser used. Is there any way to scale plot dimensions dynamically?

**Comment by Fractally** [comment]
Update: Seems like using a custom layout can fix this issue.

**Comment by djchou** [comment]
Can you elaborate with an example?

**Comment by Fractally** [comment]
Not on my dev PC now, but here is the concept: https://plot.ly/python/setting-graph-size/

So as an argument to iplot() pass a created layout with the autosize set to True (not False as in the provided link). It worked for my situation.

**Comment by santosjorge** [comment]
Hello, 
You can now use `cf.set_config_file(dimensions=(width,height))` to set the default dimensions going forward.
