### ISSUE TITLE
Offline Bubble Chart Using Cufflinks Shows All Bubbles in One Color

### ISSUE THREAD

**Issue by pybokeh** [santosjorge/cufflinks#38]
Hello,
According to this example:
https://plot.ly/ipython-notebooks/cufflinks/

I should have bubbles with different colors.  I have created an [issue](https://github.com/plotly/plotly.py/issues/443) at the plotly.py github repo, but I think this is a cufflinks issue.

**Comment by santosjorge** [comment]
Hi, you need `categories` for this.

```python
cf.datagen.bubble().iplot(kind='bubble', x='x', y='y', size='size', text='text',categories='categories')
```
