### ISSUE TITLE
Annotations location 

### ISSUE THREAD

**Issue by t0mst0ne** [santosjorge/cufflinks#43]
Accoring to http://nbviewer.jupyter.org/gist/santosjorge/f3b07b2be8094deea8c6

" Annotations can be added to the chart and these are automatically positioned correctly. "

Is it possible to set more attribution of the annotations like multiple-annotations  in plotly ?
https://plot.ly/python/text-and-annotations/#multiple-annotations 

Because  the annotations can't positioned correctly sometimes 
<img width="904" alt="2016-07-31 11 52 39" src="https://cloud.githubusercontent.com/assets/5550886/17277619/f473e2d8-5779-11e6-9672-57f209f44bb4.png">
<img width="871" alt="2016-07-31 11 52 48" src="https://cloud.githubusercontent.com/assets/5550886/17277620/f473f6ce-5779-11e6-8110-bf7ef640279c.png">

**Comment by santosjorge** [comment]
Thank @t0mst0ne , you are right this seems to happen with OHLC charts. I'll try go get a fix asap.

**Comment by t0mst0ne** [comment]
Thanks !

**Comment by rightx2** [comment]
@santosjorge When would it be fixed? I was about to post annotation problems, but found out this post already dealt with it.

**Comment by santosjorge** [comment]
I am currently working on the new version of candlesticks/ohlc charts recently released by plotly (which don't use shapes). I will ensure this work in these new type. I should have it done next week. 
Thank you.

**Comment by santosjorge** [comment]
You can now try the following 

`cf.datagen.ohlc().iplot(kind='candle',annotations={'2015-02-02':'Market Crash'})`

`cf.datagen.ohlc().iplot(kind='ohlc',annotations=[{'text':'Manual annotation','x':.2,'y':.5,'xref':'paper','yref':'paper'}])`

**Comment by t0mst0ne** [comment]
Great !

**Comment by santosjorge** [comment]
Forgot to mention you can also customise how they look:

`cf.datagen.ohlc().iplot(kind='ohlc',
                        annotations=[{'text':'Manual annotation','x':.2,'y':.5,'xref':'paper','yref':'paper'},
                                    {'text':'Another annotation','x':.5,'y':.7,'xref':'paper','yref':'paper'}],
                       fontcolor='blue',fontsize=15,textangle=-45,ay=-100)`
