### ISSUE TITLE
secondary y axis title?

### ISSUE THREAD

**Issue by rmarren1** [santosjorge/cufflinks#49]
I see there is an option to have a secondary y axis here: https://plot.ly/pandas/multiple-axes/
but there does not seem to be a way to add a title for the second axis, only the first one.

**Comment by samvasko** [comment]
A possible workaround:
```Python
fig = data.figure(secondary_y="test", yTitle="axis1")
fig.layout.yaxis2.title = "axis2"
data.iplot(data=fig.data, layout=fig.layout)
```

**Comment by santosjorge** [comment]
Thank you @samvasko 

You can now use 
`fig = data.figure(secondary_y="test", secondary_y_title="axis 2 title")`
