### ISSUE TITLE
Violin plot ?

### ISSUE THREAD

**Issue by t0mst0ne** [santosjorge/cufflinks#50]
Does anyone think violin plot useful ?
https://plot.ly/python/violin-plot/

**Comment by santosjorge** [comment]
Interesting - yes will definitely try to add them soon.

**Comment by jpoles1** [comment]
@santosjorge have you been working on this feature? I was looking for a way to contribute to this project, and was thinking I might be able to try and tackle this!

**Comment by jpoles1** [comment]
@t0mst0ne @santosjorge I was procrastinating on doing other work, so I wrote up some code to get violin plots working! 

Demo can be seen [here](http://nbviewer.jupyter.org/github/jpoles1/cufflinks/blob/master/Cufflinks%20Tutorial%20-%20Chart%20Gallery.ipynb#Violin-Plot)

**Comment by santosjorge** [comment]
This is now supported on 0.13.2
see `cf.help('violin')`

**Comment by bensdm** [comment]
i have not been able to make a violin plot, even the example in the documentation is not working properly, any clean example anywhere? thanks
