### ISSUE TITLE
what do the colors represent in the bubble chart?

### ISSUE THREAD

**Issue by chriddyp** [santosjorge/cufflinks#6]
```
import pandas as pd
df = pd.read_csv('http://www.stat.ubc.ca/~jenny/notOcto/STAT545A/examples/gapminder/data/gapminderDataFiveYear.txt', sep='\t')
df2007 = df[df.year==2007]

df2007.iplot(kind='bubble', x='gdpPercap', y='lifeExp', size='pop', text='country', filename='cufflinks/simple-bubble-chart')
```

![](https://plot.ly/~cufflinks/70.png)

I think I expected all of these points to have the same color

**Comment by saj1919** [comment]
Hi, is it possible to get multicolor bubble plot by passing some variable (Tried 'color' but it is giving only first color in list passed). Sometimes it looks good with multiple colors rather than single tone.
