### ISSUE TITLE
Trouble with TA Lib

### ISSUE THREAD

**Issue by dharamsk** [santosjorge/cufflinks#62]
I just installed this for the first time, and having trouble using it. 

The error I'm getting is "no module named talib" when I import cufflinks. 

I ran `brew install talib`. Are there other steps involved? Running pip install TA-Lib also fails on the `gcc` command (`fatal error: 'ta-lib/ta_defs.h' file not found`).

How can I get a hold of v0.10 in the meantime? I'd love to take this for a spin.

**Comment by Netherdrake** [comment]
This worked for me:

Dockerfile from Python 3.5.3
```
# install talib
RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
RUN tar -xzf ta-lib-0.4.0-src.tar.gz
WORKDIR /ta-lib
RUN ls
RUN ./configure
RUN make
RUN make install


RUN pip install TA-lib
```

**Comment by saltygk** [comment]
I faced with the same issue but solved thanks to @Netherdrake with one more thing.

After executing the above commands, I had the error `ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory` described in [talib issue#6](https://github.com/mrjbq7/ta-lib/issues/6)

so with `LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"`, i can import cufflinks as well as talib. Thank you!

my environment is like this.
Python 2.7.13 :: Anaconda custom (64-bit), CentOS Linux release 7.2.1511 (Core),

**Comment by dharamsk** [comment]
y'all are rockstars. Thank you. 

I'm on Python 2.7.10 :: Anaconda 2.5.0 (x86_64) on mac osx 10.11.6

I didn't even need to run @saltygk's command, it just worked after running that set of commands. 

My issue was the installation instructions on the [TA-Lib documentation](http://ta-lib.org/d_api/d_api.html) are wrong (or I was reading the wrong set of instructions). I emailed them letting them know.

**Comment by sdb418** [comment]
I did all the step mentioned by @dharamsk but I am still facing issues. 

 
![screen shot 2017-06-17 at 4 32 53 pm](https://user-images.githubusercontent.com/22182372/27256150-f1559b3e-537a-11e7-8c5c-2afd9888f157.png)

I am on python 3.6 mac osx 10.12.5

**Comment by MaximusIndus** [comment]
I have exactly the same issue as  @sdb418 but while installing TA-Lib 0.4.17 -

- I am on Linux hosted server (Godaddy Deluxe, which prob runs on CentOS)
- Currently installed Python 3.6.2 on virtual env. the original is 2.6.6
- I have tried instructions as shown on [this page ](https://blog.csdn.net/caib1109/article/details/78119615) 
- Have managed to install ta (older version of talib 0.4.0 i think)

Any assistance would be great!
Thanks.
