### ISSUE TITLE
Trouble with TA-lib

### ISSUE THREAD

**Issue by sdb418** [santosjorge/cufflinks#63]
I tried this steps by @Netherdrake 

# install talib
RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
RUN tar -xzf ta-lib-0.4.0-src.tar.gz
WORKDIR /ta-lib
RUN ls
RUN ./configure
RUN make
RUN make install

RUN pip install TA-lib

**Still getting this error**

![screen shot 2017-06-17 at 4 32 53 pm](https://user-images.githubusercontent.com/22182372/27256150-f1559b3e-537a-11e7-8c5c-2afd9888f157.png)

I am on python 3.6 mac osx 10.12.5

**Comment by santosjorge** [comment]
HI @sdb418 - Have you pre-installed the C library for ta-lib? 

`brew install ta-lib`

This should be done before running the install for cufflinks

**Comment by sdb418** [comment]
Yes I have done that. Still the same error

**Comment by santosjorge** [comment]
Strange the first line on your screenshot should only come up if it is not installed. 
Before there was a typo on the readme. The brew library should have a hyphen on it. Can you uninstall/reinstall?

**Comment by sdb418** [comment]
@santosjorge Thanks it worked. 


![screen shot 2017-06-21 at 1 48 10 pm](https://user-images.githubusercontent.com/22182372/27398630-5bc06c28-5688-11e7-87fb-d4ae24e2d01c.png)

**Comment by santosjorge** [comment]
👍🏻
