### ISSUE TITLE
Simple moving average not being displayed

### ISSUE THREAD

**Issue by kcavagnolo** [santosjorge/cufflinks#68]
When creating simple moving average figures, the sma columns are not displaying in the latest version of cufflinks. There is data in the columns.

My environment:
```
CPython 3.5.2
IPython 6.1.0

jupyter 1.0.0
notebook 5.0.0
pandas 0.19.2
matplotlib 2.0.2
plotly 2.0.14
cufflinks 0.12.0

compiler   : GCC 5.4.0 20160609
system     : Linux
release    : 4.4.0-87-generic
machine    : x86_64
processor  : x86_64
CPU cores  : 4
interpreter: 64bit
host name  : ubuntu
```

The commands to reproduce:
```python
import pandas as pd
import numpy as np
import matplotlib as mpl
import plotly
import plotly.plotly as py
import plotly.tools as tls
import plotly.graph_objs as go
import cufflinks as cf
cf.datagen.lines(1,500).ta_plot(study='sma',
                                periods=[13,21,55],
                                title='Simple Moving Averages',
                                world_readable=True)
```

[The resulting figure and data](https://plot.ly/~kcavagnolo/1055/simple-moving-averages/)

![plotly figure](https://plot.ly/~kcavagnolo/1055.png)

**Comment by pranavtumkur** [comment]
I am facing the same issue and I see that this issue has been closed. But sadly I do not see an answer posted. Could someone help me? @santosjorge @kcavagnolo
