### ISSUE TITLE
Possibility to pass an explicit list of bins to `df.iplot(kind='hist', ...)`

### ISSUE THREAD

**Issue by lucainnocenti** [santosjorge/cufflinks#70]
See [this question on SE](https://stackoverflow.com/q/45784591/4063051) for major details.

Basically, it seems that the `bins` parameter only accepts an integer, to be interpreted as the total number of bins in the plot. This is a problem when plotting multiple histograms with different data ranges because they get binned indipendently and thus often inconsistently (see above post).

This seems to be confirmed in (what seems to me to be) the [relevant section of the code](https://github.com/santosjorge/cufflinks/blob/ed3e666a017c869ef1c85a05dcdae5e222509b5e/cufflinks/plotlytools.py#L829-L833).

Is there another intended way to explicitly set the bins, like can be done in `matplotlib`/`pandas` directly with the `bins` parameter, or in `plotly` with `xbins`?

**Comment by santosjorge** [comment]
HI @lucainnocenti  - I have replied on SE. Please let me know if this is what you were looking for.

**Comment by lucainnocenti** [comment]
looks great, thanks!
