### ISSUE TITLE
'categories' with kind='bar'

### ISSUE THREAD

**Issue by jackparmer** [santosjorge/cufflinks#8]
I expected this to work, but I think 'categories' doesn't support bar charts yet.

![image](https://cloud.githubusercontent.com/assets/1865834/9123155/c33bdb06-3c5b-11e5-9cad-70800822df53.png)

**Comment by santosjorge** [comment]
Chris - I'll do this asap. I just want to confirm that you would be expecting the same as the output you get by doing:

```python
df.set_index('word').iplot(kind='bar',barmode='group')
```
over that same DataFrame.

**Comment by santosjorge** [comment]
Fixed in v0.6
