### ISSUE TITLE
Color generation example fails

### ISSUE THREAD

**Issue by jwhendy** [santosjorge/cufflinks#80]
Should this example from [this ipynb](https://github.com/santosjorge/cufflinks/blob/master/Cufflinks%20Tutorial%20-%20Colors.ipynb) work for me?

```
import cufflinks as cf
gen=cf.colors.colorgen()
outputColors=[gen.next() for _ in range(len(df))]
cf.colors.color_table(outputColors)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-106-8cab56c26750> in <module>()
      1 import cufflinks as cf
      2 gen=cf.colors.colorgen()
----> 3 outputColors=[gen.next() for _ in range(len(df))]
      4 cf.colors.color_table(outputColors)

<ipython-input-106-8cab56c26750> in <listcomp>(.0)
      1 import cufflinks as cf
      2 gen=cf.colors.colorgen()
----> 3 outputColors=[gen.next() for _ in range(len(df))]
      4 cf.colors.color_table(outputColors)

AttributeError: 'generator' object has no attribute 'next'
```

**Comment by ShenTungHuang** [comment]
Hello Hendy

Excuse for my poor English, I'm not totally understand your question.
But what is your variable "df" in your code, I think it's empty so
"outputColors=[gen.next() for _ in range(len(df))]" has error.


Have a nice day
ST, H

2017-12-24 12:10 GMT+08:00 John Hendy <notifications@github.com>:

**Comment by jwhendy** [comment]
Sorry about making it dependent on something else... please try this:

```
import cufflinks as cf
gen=cf.colors.colorgen()
outputColors=[gen.next() for _ in range(5)]
```

Hmm. Actually, silly me. Looks to be a `python2` vs. `python3` issue. That said, might be best to see if your code could be made version agnostic.

See [this SO question](https://stackoverflow.com/questions/1073396/is-generator-next-visible-in-python-3-0). The `python3` equivalent is:
```
outputColors=[next(gen) for _ in range(5)]
```

**Comment by ShenTungHuang** [comment]
Hello Hendy

It can work and my environment is Python3 with Jupyter notebook.

[image: 內置圖片 1]


Have a nice day
ST, H

2017-12-26 9:04 GMT+08:00 John Hendy <notifications@github.com>:

**Comment by jwhendy** [comment]
This works for you on `python3`?
```
import cufflinks as cf
gen=cf.colors.colorgen()
outputColors=[gen.next() for _ in range(5)]
```

More details:
```
$ python --version
Python 3.6.3

# after running the above:
>>> type(gen)
<class 'generator'>

>>> dir(gen)
['__class__', '__del__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__name__', '__ne__', '__new__', '__next__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'close', 'gi_code', 'gi_frame', 'gi_running', 'gi_yieldfrom', 'send', 'throw']
```

**Comment by ShenTungHuang** [comment]
Hello Hendy

Sorry and forgive my fool mistake
[image: 內置圖片 1]

Have a nice day
ST, H

2017-12-26 10:09 GMT+08:00 John Hendy <notifications@github.com>:
