### ISSUE TITLE
MACD([12,26]) and MACD SIGNAL (9) seem to be swapped

### ISSUE THREAD

**Issue by mlanderdahl** [santosjorge/cufflinks#83]
`%matplotlib inline`
`import pandas as pd`
`import cufflinks as cf`
`import requests`
`from plotly.offline import download_plotlyjs, init_notebook_mode`
`init_notebook_mode(connected=False)`
`cf.set_config_file(world_readable=False, offline=True)`

`url = r'https://min-api.cryptocompare.com/data/histohour?fsym=ADA&tsym=BTC&aggregate=3&e=Binance'`
`data = requests.get(url).json()['Data']`
`df = pd.DataFrame(data)`

`qf=cf.QuantFig(df,title='First Quant Figure',legend='top',name='GS')`
`qf.add_ema([20, 5],width=2,color=['green','lightgreen'],legendgroup=True)`
`qf.add_rsi(periods=20,color='java')`
`qf.add_volume()`
`qf.add_macd()`
`qf.iplot()`

**Looks like the MACD signal is the blue line, instead of the red one shown on the legend.**

![image](https://user-images.githubusercontent.com/3090916/35387423-d8a36c3e-01b6-11e8-9712-4b944b1eca55.png)

**Comment by santosjorge** [comment]
Hi @mlanderdahl - they seem to be correct. I have just tested them again with the data you provided and all looks good. 

Try this to see the data only:
```
cf.ta.macd(df['close'],include=False)
```

Let me know if you have a different calc please.
