### ISSUE TITLE
Configuring plot and iplot

### ISSUE THREAD

**Issue by atalyaalon** [santosjorge/cufflinks#86]
There is no option of configuring plot and iplot in cufflinks.

For example, for removing one of the buttons in plotly.offling, it's possible to use the following:
`plotly.offline.iplot(data, config={'modeBarButtonsToRemove': ['sendDataToCloud']})`
In cufflinks, however, there is not such option.

**Comment by santosjorge** [comment]
If I understand correctly what you are after, then yes there is a way to configure this:

`help(cf.set_config_file)`

**Comment by atalyaalon** [comment]
@santosjorge I know set_config_file  but I didn't find an option to config the buttons there.
Can you show me how to perform the above action (removing the sendDataToCloud button) in cufflinks?

**Comment by EmilioEsposito** [comment]
I'm also having trouble getting this to work. I expected this to work but it throws error:

`cf.set_config_file(offline=True,
				   offline_show_link=False,
				   world_readable=True,
				   theme='ggplot',
				   modeBarButtonsToRemove=['sendDataToCloud'])`
