### ISSUE TITLE
Stack mode breaks when using cf.subplots 

### ISSUE THREAD

**Issue by idoDavid** [santosjorge/cufflinks#88]
Hi, 

When trying to use cf.subplots with figures containing stacked bar plots, the stacking breaks. can this be fixed? 

Example:

Data:
`a={'catagory':['loc1','loc2','loc3'],'dogs':[1,5,6],'cats':[3,1,4],'birds':[4,12,2]}
df1 = pd.DataFrame(a)
b={'catagory':['loc1','loc2','loc3'],'dogs':[12,3,5],'cats':[4,6,1],'birds':[7,0,8]}
df2 = pd.DataFrame(b)`

The plot I get:

`cf.subplots([df1.figure(kind = 'bar', barmode = 'stack'), 
             df2.figure(kind = 'bar', barmode = 'stack')], shape = (2,1)).iplot()`

![image](https://user-images.githubusercontent.com/35657989/36967900-a3e0aa8a-2069-11e8-8dc4-3524c0dc75f5.png)

What I want to get:

![image](https://user-images.githubusercontent.com/35657989/36967916-af79e71c-2069-11e8-9a24-19ccb400af04.png)

**Comment by jorgesantostr** [comment]
`cf.subplots` generate a new layout if no layout is specified. 
However you can do something like this:
```
fig1=df1.figure(kind='bar',barmode='stack')
fig2=df2.figure(kind='bar',barmode='stack')
cf.subplots([fig1,fig2],base_layout=fig1.layout,shape=(2,1)).iplot()
```

And this should give you what you are looking for.

**Comment by idoDavid** [comment]
Great, thanks!

**Comment by pjandrews** [comment]
This returns the following error now:
cufflinks: '0.14.5'
plotly: '3.4.2'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-166-ba686a306c3d> in <module>()
----> 1 cf.subplots([fig1,fig2],base_layout=fig1.layout,shape=(2,1)).iplot()

C:\ProgramData\Anaconda3\lib\site-packages\cufflinks\tools.py in subplots(figures, shape, shared_xaxes, shared_yaxes, start_cell, theme, base_layout, **kwargs)
    756                                              shared_xaxes=shared_xaxes, shared_yaxes=shared_yaxes,
    757                                              start_cell=start_cell, theme=theme,base_layout=base_layout,
--> 758 				             **kwargs)
    759         list_ref=(col for row in grid_ref for col in row)
    760         for i in range(len(figures)):

C:\ProgramData\Anaconda3\lib\site-packages\cufflinks\tools.py in get_subplots(rows, cols, shared_xaxes, shared_yaxes, start_cell, theme, base_layout, **kwargs)
    890         sp, grid_ref = sp.to_dict(), sp._grid_ref
    891 
--> 892         for k,v in list(layout.items()):
    893                 if 'xaxis' not in k and 'yaxis' not in k:
    894                         sp['layout'].update({k:v})

C:\ProgramData\Anaconda3\lib\site-packages\plotly\basedatatypes.py in __getattr__(self, prop)
   3690             return validator.present(self._compound_props[prop])
   3691         else:
-> 3692             return super(BaseLayoutHierarchyType, self).__getattribute__(prop)
   3693 
   3694     def __getitem__(self, prop):

AttributeError: 'Layout' object has no attribute 'items'

**Comment by pjandrews** [comment]
This works though: cf.subplots([fig1,fig2],base_layout=fig1.layout.to_plotly_json(),shape=(2,1)).iplot()

**Comment by crazybull44** [comment]
> This works though:
> 
> cf.subplots([fig1,fig2],base_layout=fig1.layout.to_plotly_json(),shape=(2,1)).iplot()

AttributeError: 'dict' object has no attribute 'iplot'

**Comment by santosjorge** [comment]
That returns a `dict`. You can do the following:

```python
cf.Figure(cf.subplots([fig1,fig2],base_layout=fig1.to_dict()['layout'],shape=(2,1))).iplot()
